import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import styles from './layout.module.scss';
import './globals.scss';
import Logo from '../../docs/logo';
import * as ProductPicker from './components/docs/ProductPicker';
import ProductPopover from '../../docs/popover';

const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--font-sans',
});

const jetbrainsMono = JetBrains_Mono({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-mono',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${inter.variable} ${jetbrainsMono.variable}`}>
                <nav className={styles.appbar}>
                    <Logo />

                    <ProductPicker.Root>
                        <ProductPicker.Trigger asChild>
                            <button className={styles.pickerButton}>
                                <h1>
                                    <span className={styles.appbarName}>
                                        NewDocs
                                    </span>
                                </h1>

                                <svg
                                    xmlns='http://www.w3.org/2000/svg'
                                    viewBox='0 0 16 16'
                                    width='16'
                                    height='16'
                                >
                                    <path d='M12.78 5.22a.749.749 0 0 1 0 1.06l-4.25 4.25a.749.749 0 0 1-1.06 0L3.22 6.28a.749.749 0 1 1 1.06-1.06L8 8.939l3.72-3.719a.749.749 0 0 1 1.06 0Z'></path>
                                </svg>
                            </button>
                        </ProductPicker.Trigger>

                        <ProductPicker.Anchor />

                        <ProductPicker.Content align='center' sideOffset={16}>
                            <ProductPopover />
                        </ProductPicker.Content>
                    </ProductPicker.Root>
                </nav>

                {children}
            </body>
        </html>
    );
}
